name: Publish Bicep to Github Pages

on:
  push:
    branches:
      - main  # Set a branch to deploy
  pull_request:

defaults:
  run:
    shell: pwsh
jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Bicep
        uses: anthony-c-martin/setup-bicep@v0.1

      - name: Build SOC Bicep
        run: bicep build ./modules/SOC.bicep --outdir out

      - name: Build SOC Playbook Bicep
        run: bicep build ./modules/SOC-playbook.bicep --outdir out

      - name: Build SOC Playbook Bicep
        run: bicep build ./modules/SOC-playbook-rg.bicep --outdir out

      - name: Create SOC MG Template
        run: |
          Copy-Item out/SOC.json ./modules/SOC.json
          (Get-Content -Raw out/SOC.json).Replace('subscription','managementGroup')
          | Set-Content out/SOC-mg.json

      - name: Build RIMM Bicep
        run: bicep build ./modules/RIMM.bicep --outdir out

      - name: Create RIMM MG Template
        run: |
          Copy-Item out/RIMM.json ./modules/RIMM.json
          (Get-Content -Raw out/RIMM.json).Replace('subscription','managementGroup')
          | Set-Content out/RIMM-mg.json

      - name: Build Bicep
        run: bicep build ./modules/EM-subscription-Reader.bicep --outdir out

      - name: Publish to Github Pages 🚀
        uses: JamesIves/github-pages-deploy-action@v4.4.3
        with:
          branch: gh-pages # The branch the action should deploy to.
          folder: out # The folder the action should deploy.
